export const mockQuestions = [
  {
    id: "q1",
    section: "Aptitude",
    text: "Which number comes next in the sequence: 2, 4, 8, 16, ?",
    options: ["18", "24", "32", "64"],
    correctAnswer: 2,
  },
  {
    id: "q2",
    section: "Aptitude",
    text: "If 5x + 10 = 35, what is the value of x?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
  },
  {
    id: "q3",
    section: "Logical Reasoning",
    text: "All developers solve problems. Some problem solvers are designers. Which statement must be true?",
    options: [
      "All designers are developers",
      "Some developers are designers",
      "All developers are problem solvers",
      "No designers solve problems",
    ],
    correctAnswer: 2,
  },
  {
    id: "q4",
    section: "Logical Reasoning",
    text: "Find the odd one out.",
    options: ["React", "Express", "MongoDB", "Triangle"],
    correctAnswer: 3,
  },
  {
    id: "q5",
    section: "Technical",
    text: "Which HTTP method is commonly used to update part of an existing resource?",
    options: ["GET", "POST", "PATCH", "OPTIONS"],
    correctAnswer: 2,
  },
  {
    id: "q6",
    section: "Technical",
    text: "In JavaScript, which method converts a JSON string into an object?",
    options: ["JSON.parse", "JSON.stringify", "Object.from", "String.toJSON"],
    correctAnswer: 0,
  },
  {
    id: "q7",
    section: "Technical",
    text: "What does CSS flexbox primarily help with?",
    options: [
      "Database indexing",
      "One-dimensional layout alignment",
      "Server authentication",
      "Image compression",
    ],
    correctAnswer: 1,
  },
  {
    id: "q8",
    section: "General",
    text: "Which skill is most important when debugging a production issue?",
    options: [
      "Changing many files quickly",
      "Guessing the cause immediately",
      "Reading symptoms and isolating variables",
      "Ignoring logs",
    ],
    correctAnswer: 2,
  },
  {
    id: "q9",
    section: "Aptitude",
    text: "A team completes 40% of a task in 2 days. At the same rate, how long will the full task take?",
    options: ["3 days", "4 days", "5 days", "6 days"],
    correctAnswer: 2,
  },
  {
    id: "q10",
    section: "Technical",
    text: "Which database type is MongoDB?",
    options: ["Relational", "Document-oriented", "Graph-only", "Keypad"],
    correctAnswer: 1,
  },
  {
    id: "q11",
    section: "Logical Reasoning",
    text: "If MONDAY is coded as NPOEBZ, how is FRIDAY coded with the same pattern?",
    options: ["GSJEBZ", "ESHCZX", "GQJEBZ", "GSJCAY"],
    correctAnswer: 0,
  },
  {
    id: "q12",
    section: "Technical",
    text: "What is the purpose of version control?",
    options: [
      "Track and manage code changes",
      "Encrypt all network traffic",
      "Compile CSS only",
      "Replace testing",
    ],
    correctAnswer: 0,
  },
  {
    id: "q13",
    section: "General",
    text: "Which response best shows ownership in a team project?",
    options: [
      "That is not my part",
      "I will check what failed and update the team",
      "Someone else should fix it",
      "We should delete the feature",
    ],
    correctAnswer: 1,
  },
  {
    id: "q14",
    section: "Aptitude",
    text: "What is 15% of 200?",
    options: ["15", "20", "30", "45"],
    correctAnswer: 2,
  },
  {
    id: "q15",
    section: "Technical",
    text: "Which React hook is used to manage component state?",
    options: ["useState", "useRoute", "useServer", "useStyle"],
    correctAnswer: 0,
  },
];
