create table if not exists public.candidate_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  email text not null unique,
  application_number text not null,
  full_name text not null,
  date_of_birth date not null,
  attendance text not null,
  join_reason text not null,
  primary_department text not null,
  secondary_department text not null,
  other_societies text not null,
  recruit_reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_candidate_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_candidate_profiles_updated_at on public.candidate_profiles;

create trigger set_candidate_profiles_updated_at
before update on public.candidate_profiles
for each row
execute function public.set_candidate_profiles_updated_at();

alter table public.candidate_profiles enable row level security;

drop policy if exists "Users can view their profile" on public.candidate_profiles;
create policy "Users can view their profile"
on public.candidate_profiles
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their profile" on public.candidate_profiles;
create policy "Users can insert their profile"
on public.candidate_profiles
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their profile" on public.candidate_profiles;
create policy "Users can update their profile"
on public.candidate_profiles
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);