create table if not exists public.candidate_profiles (
  id bigint generated by default as identity primary key,

  user_id uuid not null unique
    references auth.users (id)
    on delete cascade,

  email text not null unique,
  application_number text not null,
  full_name text not null,
  date_of_birth date not null,
  attendance text not null,
  join_reason text not null,
  primary_department text not null,
  secondary_department text not null,
  other_societies text not null,
  recruit_reason text not null,
  qr_token uuid default gen_random_uuid(),
  quiz_attended boolean not null default false,
  quiz_attended_at timestamptz,
  form_locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.candidate_profiles
alter column application_number set not null,
alter column full_name set not null,
alter column date_of_birth set not null,
alter column attendance set not null,
alter column join_reason set not null,
alter column primary_department set not null,
alter column secondary_department set not null,
alter column other_societies set not null,
alter column recruit_reason set not null;

create or replace function public.set_candidate_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_candidate_profiles_updated_at on public.candidate_profiles;

create trigger set_candidate_profiles_updated_at
before update on public.candidate_profiles
for each row
execute function public.set_candidate_profiles_updated_at();

alter table public.candidate_profiles enable row level security;

drop policy if exists "Users can view their profile" on public.candidate_profiles;
create policy "Users can view their profile"
on public.candidate_profiles
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their profile" on public.candidate_profiles;
create policy "Users can insert their profile"
on public.candidate_profiles
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their profile" on public.candidate_profiles;
create policy "Users can update their profile"
on public.candidate_profiles
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.app_settings (
  key   text primary key,
  value text not null default ''
);

insert into public.app_settings (key, value)
values ('global_form_locked', 'false')
on conflict (key) do nothing;

alter table public.app_settings enable row level security;

drop policy if exists "No public access to app_settings" on public.app_settings;
create policy "No public access to app_settings"
on public.app_settings
for all
using (false);

create table if not exists public.candidate_profiles (
  id bigint generated by default as identity primary key,

  user_id uuid not null unique
    references auth.users (id)
    on delete cascade,

  email text not null unique,
  application_number text not null,
  full_name text not null,
  date_of_birth date not null,
  attendance text not null,
  join_reason text not null,
  primary_department text not null,
  secondary_department text not null,
  other_societies text not null,
  recruit_reason text not null,
  qr_token uuid default gen_random_uuid(),
  quiz_attended boolean not null default false,
  quiz_attended_at timestamptz,
  form_locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.candidate_profiles
alter column application_number set not null,
alter column full_name set not null,
alter column date_of_birth set not null,
alter column attendance set not null,
alter column join_reason set not null,
alter column primary_department set not null,
alter column secondary_department set not null,
alter column other_societies set not null,
alter column recruit_reason set not null;

create or replace function public.set_candidate_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_candidate_profiles_updated_at on public.candidate_profiles;

create trigger set_candidate_profiles_updated_at
before update on public.candidate_profiles
for each row
execute function public.set_candidate_profiles_updated_at();

alter table public.candidate_profiles enable row level security;

drop policy if exists "Users can view their profile" on public.candidate_profiles;
create policy "Users can view their profile"
on public.candidate_profiles
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their profile" on public.candidate_profiles;
create policy "Users can insert their profile"
on public.candidate_profiles
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their profile" on public.candidate_profiles;
create policy "Users can update their profile"
on public.candidate_profiles
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.app_settings (
  key   text primary key,
  value text not null default ''
);

insert into public.app_settings (key, value)
values ('global_form_locked', 'false')
on conflict (key) do nothing;

alter table public.app_settings enable row level security;

drop policy if exists "No public access to app_settings" on public.app_settings;
create policy "No public access to app_settings"
on public.app_settings
for all
using (false);

create table if not exists public.slots (
  id          uuid     primary key default gen_random_uuid(),
  slot_day    smallint not null check (slot_day    between 1 and 4),
  slot_number smallint not null check (slot_number between 1 and 3),
  slot_venue  text     not null check (slot_venue  in ('LP106','LP107','LP108','LP109')),
  unique (slot_day, slot_number, slot_venue)
);

insert into public.slots (slot_day, slot_number, slot_venue)
values
  (1,1,'LP106'),(1,1,'LP107'),(1,1,'LP108'),(1,1,'LP109'),
  (1,2,'LP106'),(1,2,'LP107'),(1,2,'LP108'),(1,2,'LP109'),
  (1,3,'LP106'),(1,3,'LP107'),(1,3,'LP108'),(1,3,'LP109'),
  (2,1,'LP106'),(2,1,'LP107'),(2,1,'LP108'),(2,1,'LP109'),
  (2,2,'LP106'),(2,2,'LP107'),(2,2,'LP108'),(2,2,'LP109'),
  (2,3,'LP106'),(2,3,'LP107'),(2,3,'LP108'),(2,3,'LP109'),
  (3,1,'LP106'),(3,1,'LP107'),(3,1,'LP108'),(3,1,'LP109'),
  (3,2,'LP106'),(3,2,'LP107'),(3,2,'LP108'),(3,2,'LP109'),
  (3,3,'LP106'),(3,3,'LP107'),(3,3,'LP108'),(3,3,'LP109'),
  (4,1,'LP106'),(4,1,'LP107'),(4,1,'LP108'),(4,1,'LP109'),
  (4,2,'LP106'),(4,2,'LP107'),(4,2,'LP108'),(4,2,'LP109'),
  (4,3,'LP106'),(4,3,'LP107'),(4,3,'LP108'),(4,3,'LP109')
on conflict (slot_day, slot_number, slot_venue) do nothing;

alter table public.slots enable row level security;
drop policy if exists "Public can read slots" on public.slots;
create policy "Public can read slots"
  on public.slots for select using (true);

create table if not exists public.slot_day_dates (
  day_number  smallint primary key check (day_number between 1 and 4),
  slot_date   date
);

insert into public.slot_day_dates (day_number)
values (1),(2),(3),(4)
on conflict (day_number) do nothing;

alter table public.slot_day_dates enable row level security;
drop policy if exists "Public can read slot_day_dates" on public.slot_day_dates;
create policy "Public can read slot_day_dates"
  on public.slot_day_dates for select using (true);
drop policy if exists "No public write to slot_day_dates" on public.slot_day_dates;
create policy "No public write to slot_day_dates"
  on public.slot_day_dates for all using (false);

create table if not exists public.slot_time_schedules (
  slot_number  smallint primary key check (slot_number between 1 and 3),
  start_time   time
);

insert into public.slot_time_schedules (slot_number)
values (1),(2),(3)
on conflict (slot_number) do nothing;

alter table public.slot_time_schedules enable row level security;
drop policy if exists "Public can read slot_time_schedules" on public.slot_time_schedules;
create policy "Public can read slot_time_schedules"
  on public.slot_time_schedules for select using (true);
drop policy if exists "No public write to slot_time_schedules" on public.slot_time_schedules;
create policy "No public write to slot_time_schedules"
  on public.slot_time_schedules for all using (false);


alter table public.candidate_profiles
  drop column if exists slot_day,
  drop column if exists slot_number,
  drop column if exists slot_venue;

alter table public.candidate_profiles
  drop column if exists slot_id;

alter table public.candidate_profiles
  add column if not exists slot_id uuid references public.slots(id) on delete set null;

create index if not exists idx_candidate_slot_id on public.candidate_profiles (slot_id);

DROP TABLE IF EXISTS public.slot_day_dates CASCADE;
CREATE TABLE IF NOT EXISTS public.slot_day_dates (
  day_number  smallint primary key,
  slot_date   date
);
ALTER TABLE public.slot_day_dates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read slot_day_dates" ON public.slot_day_dates;
CREATE POLICY "Public can read slot_day_dates"
  ON public.slot_day_dates FOR SELECT USING (true);
DROP POLICY IF EXISTS "No public write to slot_day_dates" ON public.slot_day_dates;
CREATE POLICY "No public write to slot_day_dates"
  ON public.slot_day_dates FOR ALL USING (false);

DROP TABLE IF EXISTS public.slot_time_schedules CASCADE;
CREATE TABLE IF NOT EXISTS public.slot_time_schedules (
  slot_number  smallint primary key,
  start_time   time
);
ALTER TABLE public.slot_time_schedules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read slot_time_schedules" ON public.slot_time_schedules;
CREATE POLICY "Public can read slot_time_schedules"
  ON public.slot_time_schedules FOR SELECT USING (true);
DROP POLICY IF EXISTS "No public write to slot_time_schedules" ON public.slot_time_schedules;
CREATE POLICY "No public write to slot_time_schedules"
  ON public.slot_time_schedules FOR ALL USING (false);

DROP TABLE IF EXISTS public.slots CASCADE;
CREATE TABLE IF NOT EXISTS public.slots (
  id          uuid     PRIMARY KEY DEFAULT gen_random_uuid(),
  slot_day    smallint NOT NULL,
  slot_number smallint NOT NULL,
  slot_venue  text     NOT NULL CHECK (slot_venue IN ('LP106','LP107','LP108','LP109')),
  UNIQUE (slot_day, slot_number, slot_venue)
);
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read slots" ON public.slots;
CREATE POLICY "Public can read slots"
  ON public.slots FOR SELECT USING (true);

ALTER TABLE public.candidate_profiles
  DROP COLUMN IF EXISTS slot_id;
ALTER TABLE public.candidate_profiles
  ADD COLUMN IF NOT EXISTS slot_id uuid REFERENCES public.slots(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_candidate_slot_id ON public.candidate_profiles (slot_id);
